const SITE_DATA = {
  meta: {
    brand: "KURA",
    nameEn: "Kuranosuke Shiga",
    nameJa: "志賀 蔵之介",
    year: "2026",
    location: "Chofu, Tokyo",
  },
  hero: {
    eyebrow: "PORTFOLIO — STUDENT / ORGANIZER / ENGINEER",
    lines: ["Hello. I am", "Kuranosuke", "Shiga."],
    meta: [
      { label: "NAME", value: "志賀 蔵之介 / Kuranosuke Shiga" },
      { label: "SCHOOL", value: "電気通信大学 情報理工学域 Ⅱ類（融合系）" },
      { label: "BASED IN", value: "東京・調布 / Tokyo, Japan" },
    ],
    ticker: [
      "UEC",
      "U.E.C.wings",
      "u&me",
      "UEC Fencers Club",
      "ICES",
      "Crushers"
    ],
  },
  statement: {
    text: "I lead teams, build systems, and connect people. Between engineering and community, I look for the shape of an idea.",
    ja: "つくることと、人をつなぐこと。University of Electro-Communications の学生として、技術と組織の両方から「かたち」をつくっています。",
  },
  affiliations: {
    lede: "現在所属している組織と、そこで担っている役職です。代表・班長として運営に関わるものから、スタッフとして支えるものまで。",
    items: [
      {
        org: "電気通信大学",
        orgEn: "The University of Electro-Communications",
        roleLabel: "学域(学部)生 / 2026年4月入学",
        role: "情報理工学域 Ⅱ類（融合系）",
        roleEn: "School of Informatics and Engineering, Cluster II (Interdisciplinary)",
        kind: "在学 / EDUCATION",
        period: "在学中",
        lead: false,
        summary:
          "国立大学法人 電気通信大学の情報理工学域 Ⅱ類（融合系）に所属。情報学と工学を横断する領域で学んでいます。",
        tags: ["セキュリティ情報学","情報通信工学", "電子情報学", "計測・制御システム", "先端ロボティクス"],
        image: "",
        link: "https://www.uec.ac.jp/",
      },
      {
        org: "U.E.C.wings",
        orgEn: "Birdman Club",
        role: "28代 代表 兼 駆動班 班長",
        roleEn: "28th Representative & Head of the Drive Division",
        kind: "鳥人間サークル / Birdman Club",
        period: "28代",
        lead: true,
        summary:
          "電気通信大学の鳥人間サークル U.E.C.wings の28代代表。駆動部の設計/作成の他に、公式サイトの編集もしています。",
        tags: ["代表", "班長", "マネジメント", "鳥人間コンテスト", "人力飛行機", "設計"],
        image: "",
        link: "https://www.uecwings.club.uec.ac.jp/blog/",
      },
      {
        org: "u&me",
        orgEn: "Student Organization u&me",
        role: "代表",
        roleEn: "Representative",
        kind: "学生団体 / STUDENT ORG",
        period: "現在",
        lead: true,
        summary:
          "学生団体 u&me の代表。u&melistを代表するプロジェクトの企画の立ち上げから運営までを主導しています。また、様々なコンペにも参加しています。",
        tags: ["代表", "学生団体", "事業企画運営", "コンペ"],
        image: "",
        link: "",
      },
      {
        org: "UEC Fencers Club",
        orgEn: "UEC Fencers Club",
        role: "代表",
        roleEn: "Representative",
        kind: "同好会 / CLUB",
        period: "現在",
        lead: true,
        summary:
          "フェンシング同好会の代表。初代立ち上げの創設メンバーとして、大会に出場しながら2027年の学友会公認を目標に取り組んでいます。",
        tags: ["代表", "フェンシング", "サークル運営", "全国公ベスト16"],
        image: "",
        link: "https://www.instagram.com/uec_fencers/",
      },
      {
        org: "ICES",
        orgEn: "International Cultural Exchange Society",
        role: "企画運営",
        roleEn: "Member",
        kind: "留学生国際交流会サークル / CIRCLE",
        period: "現在",
        lead: false,
        summary:
          "留学生国際交流会サークル ICES に所属。留学生と日本人学生をつなぐ交流を企画/運営しています。",
        tags: ["国際交流", "イベント企画運営","留学生支援"],
        image: "",
        link: "https://www.instagram.com/uec.ices/",
      },
      {
        org: "CRUSHERS",
        orgEn: "UEC American Football Club",
        role: "アナライジング スタッフ",
        roleEn: "Analyzing Staff",
        kind: "アメリカンフットボール部 / SPORTS",
        period: "現在",
        lead: false,
        summary:
          "アメリカンフットボール部 CRUSHERS のアナライジングスタッフ。試合・練習のデータ分析でチームを支えています。",
        tags: ["データ分析", "アメフト", "スタッフ"],
        image: "",
        link: "https://www.crushers.club.uec.ac.jp/",
      },
    ],
  },
  works: {
    lede: "企画・開発・運営として関わったプロジェクトです。詳しい内容は各リンクから見られます。",
    items: [
      {
        featured: false,
        title: "機体三面図を自動で3D再現するシミュレーター",
        subtitle: "U.E.C.wings",
        year: "2026.Sep - Now",
        category: "DEVELOPING",
        role: "開発",
        summary:
          "生成AIを利用した、鳥人間サークルの機体三面図を自動で3D化するシミュレーターを開発しました。生成AIが三面図からblenderで3Dモデルを自動生成し、その3Dデータをブラウザソフトで確認してより完成形をイメージできるようにしました。22代機体Daphneのデータを利用しました。現在はAIの精度を向上させて忠実に再現できるように挑戦しています。将来的には飛行シミュレーションや風洞実験のための基盤を整えます。",
        tags: ["AI", "機体三面図", "人力飛行機", "3D化", "シミュレーター"],
        image: "assets/images/astsim02.png",
        links: [],
      },
      {
        featured: false,
        title: "人力飛行機のフライトシミュレーター",
        subtitle: "U.E.C.wings",
        year: "2026.Sep - Now",
        category: "DEVELOPING",
        role: "開発",
        summary:
          "前回のプロジェクトの、機体三面図を自動で3D化するシミュレーターで作成した機体の3Dデータを利用した、人力飛行機のフライトシミュレーターを開発しました。Unityで作成した3D空間で、実際の飛行機の挙動を再現し、飛行体験を疑似的に体験できるようにしました。",
        tags: ["AI","人力飛行機", "フライトシミュレーター"],
        image: "assets/images/daphnesim.png",
        links: [],
      },
      {
        featured: false,
        title: "u&me list",
        subtitle: "学生団体 u&me",
        year: "2026.May - Now",
        category: "SERVICE",
        role: "最高責任者",
        summary:
        "学生団体 u&me の事業「u&melist」の企画・開発・運営を統括しています。現在は実証段階に向けて準備中です。",
        tags: ["企画運営", "チーム管理"],
        image: "assets/images/uandmelist.png",
        links: [{ label: "詳しく見る", href: "", primary: true }],
      },
      {
        featured: false,
        title: "全国公フェンシング大会2026",
        subtitle: "UEC Fencers Club",
        year: "2026.Apr",
        category: "COMPETITION",
        role: "主将",
        summary:
          "東京大学駒場キャンパスで開催された全国公フェンシング大会に、UEC Fencers Club として男子フルーレ団体に出場しました。惜しくも今年の準優勝校山形大学に敗れ、ベスト16となりました。",
        tags: ["フェンシング", "大会出場", "団体戦"],
        image: "assets/images/fencing.png",
        links: [],
      },
      {
        featured: true,
        title: "鳥人間コンテスト2026",
        subtitle: "U.E.C.wings 26代",
        year: "2026.Jul",
        category: "Birdman Contest",
        role: "駆動班",
        summary:
          "私の故郷、滋賀県にある琵琶湖で毎年開催されている鳥人間コンテストで1km以上の飛行を目指して鳥人間サークルに携わりました。本戦の出場は叶いませんでしたが、テストフライトに成功したほか、現地で本戦の視察も行いました。",
        tags: ["鳥人間コンテスト", "人力飛行機"],
        image: "assets/images/wings.png",
        links: [
          { label: "公式ページ", href: "https://www.uecwings.club.uec.ac.jp/blog/", primary: true },
          { label: "大会ページ", href: "https://www.ytv.co.jp/birdman/" },
        ],
      },
      // {
      //   featured: false,
      //   title: "NEW PROJECT",
      //   subtitle: "Coming soon...",
      //   year: "NEXT",
      //   category: "SERVICE",
      //   role: "企画",
      //   summary:
      //     "現在新しい事業を構想しています・",
      //   tags: ["新事業"],
      //   image: "",
      //   links: [],
      // },
    ],
  },
  profile: {
    heading: "志賀 蔵之介 —\nKuranosuke Shiga",
    portrait: "assets/images/profile.png",
    portraitCaption: "PORTRAIT / 2026",
    paragraphs: [
      "国立大学法人 電気通信大学 情報理工学域 Ⅱ類（融合系）に在籍。情報と工学の境界にある領域を学びながら、学内では複数の団体で運営に携わっています。",
      "鳥人間サークル U.E.C.wings では28代代表 兼 駆動班班長、学生団体 u&me と UEC Fencers Club では代表を務めています。加えて ICES での国際交流イベントの企画運営、アメリカンフットボール部 CRUSHERS でのデータ分析にも取り組んでいます。",
    ],
    spec: [
      { label: "所属", value: "電気通信大学 情報理工学域 Ⅱ類（融合系）" },
      { label: "役職", value: "U.E.C.wings 28代代表 / 駆動班班長" },
      { label: "役職", value: "学生団体 u&me 代表" },
      { label: "役職", value: "UEC Fencers Club 代表" },
      { label: "活動", value: "ICES / Crushers アナライジングスタッフ" },
    ],
    focus: {
      title: "FOCUS",
      items: [
        { no: "00", name: "Learning", desc: "情報工学の習得と応用" },
        { no: "01", name: "Management", desc: "団体運営・チームマネジメント・意思決定" },
        { no: "02", name: "Engineering", desc: "人力飛行機の駆動部の設計/制作" },
        { no: "03", name: "Developing", desc: "ソフトウェア・サービス開発" },
        { no: "04", name: "Competition", desc: "複数のコンペティションに参加" },
        { no: "05", name: "Fencing", desc: "選手としてフェンシングの大会に参加" },
        { no: "06", name: "Communication", desc: "国際交流、人と人をつなぐ場づくり" },
        { no: "07", name: "Analysis", desc: "スポーツのデータ分析とフィードバック" },
      ],
    },
  },
  strip: { a: "KURA'", b: "Kuranosuke Shiga" },
  contact: {
    lines: ["Let's start", "something."],
    actions: [
      { label: "DROP ME AN EMAIL", value: "kuranosukeshiga1129@gmail.com", href: "mailto:kuranosukeshiga1129@gmail.com" },
    ],
    socials: [
      { label: "EMAIL", handle: "kuranosukeshiga1129@gmail.com", href: "mailto:kuranosukeshiga1129@gmail.com" },
      { label: "X (TWITTER)", handle: "@kuranosukeshiga", href: "https://x.com/kuranosukeshiga" },
      { label: "INSTAGRAM", handle: "@kuranosukeshiga", href: "https://www.instagram.com/kuranosukeshiga/" },
    ],
  },
  menu: [
    { label: "HOME", href: "#top", no: "00" },
    { label: "STATEMENT", href: "#statement", no: "01" },
    { label: "AFFILIATIONS", href: "#affiliations", no: "02" },
    { label: "WORKS", href: "#works", no: "03" },
    { label: "PROFILE", href: "#profile", no: "04" },
    { label: "CONTACT", href: "#contact", no: "05" },
  ],
  footer: {
    copy: "©2026 KURANOSUKE SHIGA",
    note: "DESIGNED & BUILT IN TOKYO",
  },
};
